const text=[
    `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    `t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).`,
    `contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32`,
    `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.`,
    `Proin consectetur ipsum vel est sodales hendrerit. Phasellus ullamcorper tristique sodales. Praesent nulla dui, mattis id erat sed, varius scelerisque erat. Proin augue mauris, facilisis quis arcu ac, cursus tempus erat. Praesent eleifend maximus tortor, sit amet hendrerit lectus sagittis vitae. Integer suscipit rutrum tellus et semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras laoreet sed libero sit amet aliquam.`,
    `Suspendisse aliquet ultricies nunc in lobortis. Quisque cursus nunc ut ante dignissim tristique. Etiam sed posuere odio, ac hendrerit neque. Nullam dictum ligula tempor, blandit diam id, bibendum ligula. Proin lectus sapien, hendrerit id iaculis in, eleifend eget lorem. Vivamus viverra, elit id elementum hendrerit, risus sem vulputate tellus, dictum lobortis mi odio eu velit. Nunc non dictum magna. Proin tristique vel magna a semper. Etiam eu libero ac purus rutrum porta tristique at est.`,
    `Aenean sed nibh sit amet ligula accumsan cursus. Ut sodales, nunc ut sagittis semper, dui turpis pellentesque enim, in condimentum ligula sapien at ipsum. In consequat nulla urna, ac bibendum arcu molestie at. Integer a elit elit. Nulla gravida malesuada est, vitae iaculis sapien tincidunt sit amet. Sed accumsan lacinia orci, sit amet scelerisque neque dictum mollis. Vestibulum mollis aliquet lacus, sed sagittis nisi sodales at. Mauris tempus erat nec venenatis maximus. Phasellus arcu tortor, suscipit et arcu eu, semper fermentum sem. Morbi eros nisl, consectetur at leo non, laoreet dignissim lacus. Pellentesque ut neque vel metus sollicitudin aliquet. Nulla facilisi. Nam et ultricies lacus, sed suscipit metus. Vivamus hendrerit faucibus felis, ut iaculis felis faucibus sed.`,
    `Praesent mattis mi id interdum iaculis. Nulla vitae fringilla lectus, ut ultrices diam. Quisque eget metus et justo rhoncus aliquam ac ac libero. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec rutrum suscipit iaculis. Morbi at massa et ante dictum accumsan rutrum sed nulla. Quisque nec tristique justo. Fusce pulvinar turpis ultricies venenatis ullamcorper. Nam in congue tellus. Morbi ligula purus, varius id interdum sit amet, pharetra id erat. Duis volutpat dui sit amet tellus mattis ultricies. Vestibulum laoreet egestas pulvinar.`,`Ut mollis lacus tortor, in congue ex imperdiet eget. Nulla consectetur ipsum at neque finibus, non vulputate ligula commodo. Nam scelerisque consectetur diam varius volutpat. Aliquam erat volutpat. Morbi interdum, sapien sed ullamcorper tempor, ipsum ex iaculis augue, ac pellentesque diam ligula non nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut lorem erat, vulputate vel orci id, vulputate vehicula lorem. Fusce dictum leo lacus. Aliquam erat volutpat. Donec fringilla maximus mi sit amet ultrices. Aliquam at tempus nibh, sed rhoncus felis. Integer mattis nunc vitae faucibus ullamcorper. Aliquam erat volutpat. Etiam tempus leo quis diam facilisis, laoreet porta ex gravida. Nunc ullamcorper id enim hendrerit dapibus.`,
    `Vivamus sit amet lorem vulputate, scelerisque augue vitae, congue neque. Fusce finibus lacus at hendrerit eleifend. Curabitur vehicula ex ac nunc accumsan euismod. Nulla tincidunt volutpat eleifend. Cras mollis non dui et ultrices. Quisque tempus massa ut velit placerat, in congue odio euismod. Donec varius eros at fermentum facilisis. Curabitur sagittis, arcu at tempor sodales, est purus finibus nisl, sed imperdiet lacus enim id arcu. In hac habitasse platea dictumst.`
];
const form=document.querySelector('.lorem-form');
const amount=document.querySelector('.amount');
const btn=document.querySelector(".btn");
const output=document.querySelector('.lorem-text');
form.addEventListener('submit',function(e){
    e.preventDefault();
    const value=parseInt(amount.value);
    const random=Math.floor(Math.random() * text.length);
    if(isNaN(value) || value<=0 || value>9){
        output.innerHTML=`<p class="result">${text[random]}</p>`;
    }
    else{
        let temptext=text.slice(0,value);
        console.log(temptext)
        .map(function(item){
            return `<p class="result">${item}</p>`
        })
        .join("");
    }
    console.log(value);
})